provider:
  name: openfaas
functions:
  mptosvg:
    image: ghcr.io/pandora-mccme/metapost-fn:main
    fprocess: "mptosvg"
    readonly_root_filesystem: true
    environment:
      content_type: "image/svg+xml"
    limits:
      memory: 40Mi
      cpu: 200m
    requests:
      memory: 20Mi
      requests: 100m