provider:
  name: openfaas
functions:
  mptosvg:
    image: ghcr.io/pandora-mccme/metapost-fn:main
    fprocess: "mptosvg"
    readonly_root_filesystem: true
    environment:
      content_type: "application/octet-stream"
      exec_timeout: 3m
      read_timeout: 3m
      write_timeout: 3m
    limits:
      memory: 128Mi
      cpu: 1000m
    requests:
      memory: 20Mi
      requests: 100m
